In [6]:
import pandas as pd
import json

In [8]:
df = pd.read_csv('lad_prod.csv')

count    6804.000000
mean       29.821008
std         7.452830
min        15.800000
25%        24.737500
50%        28.585000
75%        33.132500
max        77.920000
Name: value, dtype: float64

In [ ]:

df = df.pivot_table(index=['area_code', 'name'], columns='date', values='value')
df = df.reset_index()
df.to_csv('lad_prod_wide.csv', index=False)

In [7]:
s = "2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021"
l = s.split(',')
json.dumps(l)

'["2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021"]'

In [24]:
df = pd.read_csv('lad_prod.csv')

# get the median for each date
df['median'] = df.groupby('date')['value'].transform('median')
df['relative'] = df['value'] / df['median']

df.relative.describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9])

count    6804.000000
mean        1.056595
std         0.232872
min         0.653404
10%         0.834482
25%         0.904468
50%         1.000000
75%         1.148381
90%         1.333295
max         2.679053
Name: relative, dtype: float64

In [25]:

print(df.relative.describe())

df = df.drop(columns=['median'])
df['value'] = df['relative']

df = df.pivot_table(index=['area_code', 'name'], columns='date', values='value')
df = df.reset_index()

df.to_csv('lad_prod_rel_wide.csv', index=False)

count    6804.000000
mean        1.056595
std         0.232872
min         0.653404
25%         0.904468
50%         1.000000
75%         1.148381
max         2.679053
Name: relative, dtype: float64

In [29]:
df[(df[2021]>0.99) & (df[2021]<1.01)]

date,area_code,name,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
13,E06000014,York,1.236132,1.236224,1.249273,1.228331,1.201252,1.153524,1.114430,1.099335,1.097172,1.111111,1.125132,1.136340,1.138991,1.128980,1.095201,1.052167,1.012137,0.991101
15,E06000016,Leicester,0.813603,0.814609,0.851683,0.865971,0.885195,0.891810,0.902744,0.915805,0.927121,0.936482,0.934622,0.914423,0.908119,0.920728,0.951692,0.974297,0.989343,0.994602
52,E06000056,Central Bedfordshire,0.999362,1.003417,1.007063,1.004815,1.019754,1.014857,1.010640,0.993722,0.996737,1.008409,1.024956,1.030012,1.032075,1.035413,1.029426,1.013232,1.000888,0.991977
76,E07000038,North East Derbyshire,0.898618,0.886373,0.940590,0.928170,0.908664,0.877714,0.850103,0.849705,0.857868,0.891752,0.925835,0.944949,0.949215,0.928850,0.922109,0.941141,0.979278,1.007732
103,E07000078,Cheltenham,0.960680,0.948740,1.028666,1.054575,1.057305,1.040000,0.996827,0.951256,0.907179,0.888889,0.900176,0.919911,0.951554,0.966862,0.975295,0.979468,0.988159,0.996937
167,E07000146,King's Lynn and West Norfolk,1.058023,1.060231,1.058995,1.038925,1.015842,1.003429,1.006160,1.036558,1.039521,1.027017,0.988401,0.968273,0.968593,0.979532,0.988198,0.988289,0.993783,0.994311
178,E07000170,Ashfield,1.137938,1.143101,1.147902,1.125201,1.107765,1.094857,1.105096,1.124446,1.110950,1.083915,1.051318,1.023495,1.004678,0.978558,0.969001,0.966692,0.987271,0.998979
201,E07000200,Babergh,0.939426,0.936352,0.940590,0.945827,0.983376,1.008000,1.009147,0.984490,0.959028,0.955806,0.970123,0.974447,0.976612,0.978233,0.989457,1.000152,1.002664,1.000146
228,E07000235,Malvern Hills,0.997237,1.001282,0.988367,0.972311,0.960297,0.947810,0.938212,0.952733,0.957941,0.970120,0.964499,0.962442,0.965920,0.975634,0.990716,0.995894,1.001480,0.997812
231,E07000238,Wychavon,0.874814,0.882102,0.881180,0.865169,0.849208,0.840381,0.837036,0.857829,0.863307,0.883521,0.886467,0.886640,0.888740,0.902209,0.933753,0.961825,0.989343,0.999854
236,E07000243,Stevenage,1.204676,1.194361,1.269215,1.247994,1.227851,1.177905,1.144671,1.128139,1.125453,1.153337,1.160633,1.151089,1.111928,1.072450,1.031629,1.008365,1.004737,1.009774
254,E08000015,Wirral,0.966206,0.970098,1.005816,1.007223,0.999804,0.984000,0.975173,0.982275,0.973532,0.966184,0.960984,0.953524,0.949215,0.932749,0.933124,0.949962,0.982238,1.003647
273,E08000035,Leeds,1.094155,1.091414,1.143747,1.154896,1.155877,1.148571,1.138324,1.135155,1.119652,1.115047,1.105800,1.087635,1.066823,1.053606,1.042014,1.028137,1.014506,1.006565
304,E09000029,Sutton,1.296068,1.297309,1.312422,1.295345,1.257188,1.231238,1.199179,1.200517,1.179478,1.171229,1.153251,1.133939,1.122285,1.104288,1.090480,1.049430,1.018946,0.991685
314,N09000005,Derry City and Strabane,0.842508,0.867578,0.881595,0.854334,0.827303,0.763048,0.736606,0.722304,0.734953,0.754339,0.790510,0.833476,0.876044,0.907407,0.932809,0.959696,0.985790,1.001896
331,S12000019,Midlothian,0.873964,0.879966,0.864977,0.861557,0.875807,0.882286,0.892290,0.896233,0.901015,0.912507,0.940246,0.962099,0.981958,0.997726,1.011802,1.019011,1.014506,1.007148
342,S12000035,Argyll and Bute,1.019341,1.017087,1.004570,0.994382,0.999022,1.009524,1.022214,1.038405,1.043510,1.048130,1.048155,1.037558,1.030738,1.017544,1.011487,0.999848,0.999112,0.997812
352,S12000049,Glasgow City,0.926674,0.926100,0.957624,0.963082,0.973988,0.984762,0.996453,1.013294,1.014503,1.022723,1.022496,1.020751,1.012028,1.003574,0.998584,0.998327,1.006217,1.009190
360,W06000006,Wrexham,1.031668,1.030756,1.056917,1.053772,1.056914,1.062476,1.070375,1.088626,1.088470,1.088567,1.074165,1.054708,1.034414,1.012995,0.999213,0.994373,0.997632,0.998979